//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int menu_id { get; set; }
        public byte quantity { get; set; }
        public decimal unit_price { get; set; }
        public System.DateTime create_at { get; set; }
    
        public virtual Menu menu { get; set; }
        public virtual Order order { get; set; }
    }
}
